### PR TITLE
Fix links

### LINKED ISSUE #101: Fix links
- [x] Add functionality so that the links on the live site (header + footer) all link properly to the section they're referencing (if that section already exists) 
- [x] Make the HBP logo link back to the live site main page (when clicking on it from the live site) 
- [x] Make the HBP logo link back to the main site main page (when clicking on it from the main site) 
- [x] Fix issue of links not linking to the section when clicked from a different page on main site 

For ^ this one just prepend it with '/' according to Surbhi: this is what she did for the live site 
const liveSiteTabInfo: TabInfo[] = [
  { name: 'Schedule', link: '/#schedule' },
  { name: 'Mentors', link: '/#mentors' },
  { name: 'Challenges', link: '/#challenges' },
  { name: 'Resources', link: '/#resources' },
  { name: 'Team', link: '/#team' },
  { name: 'Judging', link: '/judging' }
];

https://user-images.githubusercontent.com/59738880/207781320-3f656c7f-074c-4fb4-bec6-7b243fd5c2f4.mov

### PR DESCRIPTION
**Pull request by deanframe**
<Summary line - One sentence describing your intended set of changes>

Fixes #101 

Changelist:

- completes tasks listed in ticket
- also adds padding so that headers of page sections aren't cut off, and adds smooth scrolling behavior

Tested:

- locally FF + Chrome

### CODE REVIEW

File: live-site/lib/data.ts [hunk 1]
```diff
@@ -1,11 +1,11 @@
 import { TabInfo } from './types';
 
 const liveSiteTabInfo: TabInfo[] = [
-  { name: 'Schedule', link: '#schedule' },
-  { name: 'Mentors', link: '#mentors' },
-  { name: 'Challenges', link: '#challenges' },
-  { name: 'Resources', link: '#resources' },
-  { name: 'Team', link: '#team' }
+  { name: 'Schedule', link: '/#schedule' },
```
Comment (jzhzhang66) [inline live-site/lib/data.ts:5]: hmm ok this actually isn't working for me - I don't see it scrolling to the correct location when I click on the links from /code-of-conduct

@surbhi-gulati or @deanframe is that ^ case working for you guys with this?

**Review by jzhzhang66 — CHANGES_REQUESTED** [review]
Overall looks great!!! Thanks Dean! love the SMOOOOOOOTHness and thank you for taking initiative to fix the cut off issue!!!<333

I am still having the issue with not being directly redirected to the section when clicking from coc page tho that's the only comment I left!

File: live-site/lib/data.ts (hunk 1 above)
Comment (deanframe) [reply live-site/lib/data.ts:5]: tbh not quite sure what you mean, can you attach a video?

Comment (jzhzhang66) [reply live-site/lib/data.ts:5]: Yep! When I click calendar from the code of condcut page it should link to the section on the first click not the second
https://user-images.githubusercontent.com/59738880/208748263-ae0e91b5-c2d6-4ca8-b156-030f80d7e6ea.mov

**Review by jhylisa666 — CHANGES_REQUESTED** [review]
Resources on the live site doesn't work for me somehow. 
otherwise GREAT WORK KING

File: shared-ui/components/footer/Footer.tsx [hunk 2]
```diff
@@ -31,7 +31,7 @@ const Footer: React.FC<FooterProps> = ({ tabs, isDay }) => {
           <StyledFooterText>
             HackBeanpot, Inc. is a registered 501(c)(3) organization.
           </StyledFooterText>
-          <StyledFooterTextLink href="https://hackbeanpot.com/code-of-conduct/">
+          <StyledFooterTextLink href='/code-of-conduct'>
```
Comment (deanframe) [inline shared-ui/components/footer/Footer.tsx]: we probably shouldn't link to the prod site from dev/vercel - this is the change that makes this PR add another copy of the code of conduct page to the live site. might be a better way to do this with gatsby?

File: live-site/lib/data.ts (hunk 1 above)
Comment (deanframe) [reply live-site/lib/data.ts:5]: fixed this in a super hacky way - see gatsby-browser.ts. the code in that file runs immediately, but our page takes longer to load. so the code wouldn't be able to find the section of the page to scroll to, as it hadn't loaded in yet. so i added the timeout to make the code run after a second (should i make this longer to accommodate for people with really slow computers?).

Our page most likely takes longer to load because we are not using gatsby's native `Link` component  ([docs](https://www.gatsbyjs.com/docs/reference/built-in-components/gatsby-link/)) - we are using normal anchor tags `<a> <a/>` instead. some tech debt to fix for the future. reason i didn't fix this now is that we are styling these anchor tags in the shared ui folder, and that folder does not have access to gatsby components since gatsby is only in the package.json for the main-site and live-site folders. I didn't want to import the whole library just to use one component so I left it as is.

File: shared-ui/components/footer/Footer.tsx (hunk 2 above)
Comment (jzhzhang66) [reply shared-ui/components/footer/Footer.tsx]: I think we have it like this bc David / Sreya wanted the code-of-conduct page to just be on the main site instead of having the page also on the live-site

Comment (jzhzhang66) [reply shared-ui/components/footer/Footer.tsx]: But idk do you think that would be confusing for the user? If they are on the live site, click the code of conduct and then end up on the other site that kind of looks like the live site but isn't?

**Review by jhylisa666 — APPROVED** [review]
LGTM HEHEHEHE

File: live-site/gatsby-browser.ts [hunk 3]
```diff
@@ -0,0 +1,18 @@
+import type { GatsbyBrowser } from 'gatsby';
+
+export const shouldUpdateScroll: GatsbyBrowser["shouldUpdateScroll"] = ({
```
Comment (jzhzhang66) [inline live-site/gatsby-browser.ts]: if this scrolling isn't working, could we please get rid of this file?

**Comment by jzhzhang66** [comment]
Also could we please change the code-of-conduct back to just being on the main-site? Unless you think it makes more sense for it to be on both sites then we can discuss??

**Review by jzhzhang66 — CHANGES_REQUESTED** [review]

File: live-site/src/pages/index.tsx [hunk 4]
```diff
@@ -55,14 +54,13 @@ const IndexPage: React.FC = () => {
...
       )}
-      <Background isDay={true} />
       <ComingUpSection />
       <WelcomeSection />
       <EventScheduleSection />
       <ResourcesSection />
       <MeetTheTeamSection />
       <MentorsSection />
-      <Footer tabs={liveSiteTabInfo} isDay />
+      <Footer tabs={liveSiteTabInfo} isDay={true} />
```
Comment (jzhzhang66) [inline live-site/src/pages/index.tsx]: if the prop is true we can just leave it as isDay I think??? 

it's the same thing as isDay={true}

**Review by jzhzhang66 — APPROVED** [review]
APPROVING W COMMENT
