### PR TITLE
Livesite bg header footer mainsite fixes

### LINKED ISSUE #53: Add background, header, and footer to live-site + small main-site fixes
The purpose of this ticket is to start setting up the live-site + add some small things for the main-site!! 

LIVE-SITE:
NOTE: you can pretty much just reference how this is done on the main-site
- [x] Add in the day backgrounds (desktop + mobile) into the live-site (the background toggling will be for a separate ticket so don't worry about that)
- [x] Add in header 
- [x] Add in footer 
- [x] For the links on header + footer, reference the ones on the live-site design figma https://www.figma.com/file/xLGm0VA2EKkryPoqOYxl5p/2023-Live-Site-Designs

MAIN-SITE: 

- [x] Add in favicon
- [x] Add logic on mobile so that when you open the menu and click on something, it exits from the menu. Right now it doesn't exit from the menu.

### PR DESCRIPTION
**Pull request by srazh**
Started Live site and fixed minor main site issues

Fixes #53 

Changelist:

- added header and footer (with updated live site links) to live site
- added background (svg)
- added favicon
- fixed mobile menu issue (will close automatically once you click a link now)

Notes:

- important: background uses svg (I talked to Judy about this bug and we are using svg for now so we can work on live site sections next sprint)

Tested:

- local host 8000

Screenshots & Screencasts:

https://user-images.githubusercontent.com/63278213/202075522-99f42875-35c0-4bfc-99c3-ab57d61bb505.mov

https://user-images.githubusercontent.com/63278213/202075542-df4fc898-7ca6-4b15-8dec-421ace188c43.mov

Screen Shot 2022-11-15 at 10 05 24 PM

### CODE REVIEW

**Review by jzhzhang66 — APPROVED** [review]
LGTM for some reason the build is failing though we shuold fix this

File: shared-ui/lib/typography.ts [hunk 1]
```diff
@@ -0,0 +1,69 @@
+import styled from 'styled-components';
```
Comment (surbhi-gulati) [inline shared-ui/lib/typography.ts:1]: lgtm other than failing test, do we want to delete the duplicated version of this file / redirect to this shared version since we already created styled font types somewhere else in the repo before?

**Review by surbhi-gulati — CHANGES_REQUESTED** [review]

File: shared-ui/lib/typography.ts (hunk 1 above)
Comment (jzhzhang66) [reply shared-ui/lib/typography.ts:1]: nice catch!
